name: Build and Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Create .nojekyll
        run: touch .nojekyll

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: . # The folder that should be deployed
          branch: gh-pages # The branch that should be deployed
          clean: true # Remove existing files from the deploy branch before deploying